version: '3.8'

services:
  app:
    build: .
    container_name: face_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: chirudb
      MYSQL_ROOT_PASSWORD: Chirag@2004
    ports:
      - "3308:3306"
